//
//  OrbitingThreat.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/22/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "Threat.h"


/*!
	@class		OrbitingThreat
	@abstract	This class is generated by CocoaTranslator. Annotated as: 
				@simpl_inherit
				@xml_tag
	@discussion	missing java doc comments or could not find the source file.
*/
@interface OrbitingThreat : Threat
{
}



@end

