//
//  PatrollingThreat.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/21/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "PatrollingThreat.h"

@implementation PatrollingThreat

- (void) dealloc {
	[super dealloc];
}



@end

