//
//  RepellableThreat.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/22/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "RepellableThreat.h"

@implementation RepellableThreat

- (void) dealloc {
	[super dealloc];
}



@end

