//
//  SingleSeekerThreat.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/22/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "SingleSeekerThreat.h"

@implementation SingleSeekerThreat

@synthesize targetOrd;
- (void) dealloc {
	[super dealloc];
}

- (void) setTargetOrdWithReference: (int *) p_targetOrd {
	targetOrd = *p_targetOrd;
}



@end

