//
//  GameData.m
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/21/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import "GameData.h"

@implementation GameData

@synthesize timestamp;
@synthesize cycRem;
@synthesize paused;
@synthesize loaded;
@synthesize over;
@synthesize running;
@synthesize won;
@synthesize threats;
@synthesize score;
- (void) dealloc {
	[threats release];
	[super dealloc];
}

- (void) setTimestampWithReference: (long *) p_timestamp {
	timestamp = *p_timestamp;
}

- (void) setCycRemWithReference: (int *) p_cycRem {
	cycRem = *p_cycRem;
}

- (void) setPausedWithReference: (bool *) p_paused {
	paused = *p_paused;
}

- (void) setLoadedWithReference: (bool *) p_loaded {
	loaded = *p_loaded;
}

- (void) setOverWithReference: (bool *) p_over {
	over = *p_over;
}

- (void) setRunningWithReference: (bool *) p_running {
	running = *p_running;
}

- (void) setWonWithReference: (bool *) p_won {
	won = *p_won;
}

- (void) setScoreWithReference: (double *) p_score {
	score = *p_score;
}



@end

