//
//  GameData.h
//  ecologylabXML
//
//  Generated by CocoaTranslator on 06/22/11.
//  Copyright 2011 Interface Ecology Lab. 
//

#import <Foundation/Foundation.h>
#import "ElementState.h"


/*!
	@class		GameData
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface GameData : ElementState
{
	/*!
		@var		timestamp
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	long timestamp;

	/*!
		@var		cycRem
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	int cycRem;

	/*!
		@var		paused
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	bool paused;

	/*!
		@var		loaded
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	bool loaded;

	/*!
		@var		over
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	bool over;

	/*!
		@var		running
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	bool running;

	/*!
		@var		won
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	bool won;

	/*!
		@var		threats
		@abstract	Annotated as : 
					@simpl_classes
					@simpl_collection
		@discussion	missing java doc comments or could not find the source file.
	*/
	NSMutableArray *threats;

	/*!
		@var		score
		@abstract	Annotated as : 
					@simpl_scalar
		@discussion	missing java doc comments or could not find the source file.
	*/
	double score;

}

@property (nonatomic, readwrite) long timestamp;
@property (nonatomic, readwrite) int cycRem;
@property (nonatomic, readwrite) bool paused;
@property (nonatomic, readwrite) bool loaded;
@property (nonatomic, readwrite) bool over;
@property (nonatomic, readwrite) bool running;
@property (nonatomic, readwrite) bool won;
@property (nonatomic, readwrite, retain) NSMutableArray *threats;
@property (nonatomic, readwrite) double score;

- (void) setTimestampWithReference: (long *) p_timestamp;
- (void) setCycRemWithReference: (int *) p_cycRem;
- (void) setPausedWithReference: (bool *) p_paused;
- (void) setLoadedWithReference: (bool *) p_loaded;
- (void) setOverWithReference: (bool *) p_over;
- (void) setRunningWithReference: (bool *) p_running;
- (void) setWonWithReference: (bool *) p_won;
- (void) setScoreWithReference: (double *) p_score;

@end

