#import "TranslationScope.h"
#import "GameData.h"
#import "PatrollingThreat.h"
#import "RepellableThreat.h"
#import "Threat.h"
#import "OrbitingThreat.h"
#import "Entity.h"
#import "SingleSeekerThreat.h"

#import <Foundation/Foundation.h>


/*!
	@class		gamedata
	@abstract	This class is generated by CocoaTranslator. 
	@discussion	missing java doc comments or could not find the source file.
*/
@interface gamedata : NSObject
{
}

+ (TranslationScope *) translationScope;


@end

